apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: default
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "asdjflkasdjfd$#E*(R*(REDFJDFDFKJDKFJDLKFJDFdsfjdslafjDF***"))"
  JWT_REFRESH_SECRET: "D@##KFJDLKFJDKLFJ KDJFdsfsdjflasdjflksad jfsdlkafjDF***"
  DATABASE_URL: "postgres://auth_user:auth_pass@postgres-svc:5433/auth_db?sslmode=disable"
  REDIS_ADDR: "redis-svc:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-svc:5672/"
